"""add shipment_date and payment_method to completed_orders

Revision ID: 43ce81895603
Revises: d2bf140c5762
Create Date: 2025-04-25 18:54:42.981088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43ce81895603'
down_revision: Union[str, None] = 'd2bf140c5762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completed_orders', sa.Column('shipment_date', sa.Date(), nullable=True))
    op.add_column('completed_orders', sa.Column('payment_method', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('completed_orders', 'payment_method')
    op.drop_column('completed_orders', 'shipment_date')
    # ### end Alembic commands ### 