"""add status string column to completed_orders

Revision ID: b1d8f0a7e2c3
Revises: 43ce81895603
Create Date: 2025-04-26 10:30:00.000000 # Placeholder date

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Import the enum for default value reference
from models import CompletedOrderStatus


# revision identifiers, used by Alembic.
revision: str = 'b1d8f0a7e2c3'
down_revision: Union[str, None] = '43ce81895603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completed_orders', sa.Column('status', sa.String(length=50), nullable=False, server_default=CompletedOrderStatus.COMPLETED.value))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('completed_orders', 'status')
    # ### end Alembic commands ### 