"""Merge Heroku heads 7539 and 48ef

Revision ID: merge_heroku_heads
Revises: 753906409270, 48ef864841f3
Create Date: 2025-04-29 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'merge_heroku_heads' 
# Merge the two heads identified on Heroku
down_revision = ('753906409270', '48ef864841f3')
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 